### PR TITLE
Constraints

### PR DESCRIPTION
**Pull request by alinamarasca**

### CODE REVIEW

**Review by erkamguresen — COMMENTED** [review]
Do we have to have same constraints.md in two different locations?

**Review by mayuri2510 — DISMISSED** [review]
Approve

**Comment by alinamarasca** [comment]
> Do we have to have same constraints.md in two different locations?

@erkamguresen What do you mean under 'location'?

**Comment by erkamguresen** [comment]
> > Do we have to have same constraints.md in two different locations?
> 
> @erkamguresen What do you mean under 'location'?

one is in main folder one is in planning folder.

**Review by mayuri2510 — APPROVED** [review]
Approve

**Review by erkamguresen — APPROVED** [review]

**Pull request merged**
