### PR TITLE
Wireframe added, index.html map code warning added, favicon code corr…

### PR DESCRIPTION
**Pull request by erkamguresen**
Wireframe added, index.html map code warning added, favicon code corrected

### CODE REVIEW

**Review by alinamarasca — CHANGES_REQUESTED** [review]
Wireframe scheme is good BUT should be no code. You can add dummy text and things like 'logo' or 'menu" etc
[updated example inn 'about trees' project](https://github.com/HackYourFutureBelgium/incremental-development/blob/master/planning-and-collaborating/example-all-about-trees/planning/development-strategy.md)

**Comment by erkamguresen** [comment]
Ha ha super, when I checked it was like what I did . I think they are also work in progress.

**Comment by erkamguresen** [comment]
Hi @alinamarasca ; I changed the wireframe. But thinking it is the development strategy add talking about classes and their names but not writing the code is huge contradiction. Why we don't write code in the backlog? Because it is shared and prepared with the customer . And What about development strategy ? do we share them and discuss with customer or not? if we share why we write css class names if we don't why we should not use main Html tags to express the design?

**Review by alinamarasca — APPROVED** [review]

**Comment by alinamarasca** [comment]
@erkamguresen I don't know, but maybe we ask Evan on Sunday? Or on this 'Duscussions' page. Everything I know you can read in message and thread I resent to you on Slack. 

Very cute wireframe, by the way)

**Comment by erkamguresen** [comment]
Thanks... for the question I asked on slack and we move to the discussion. you can find there

**Pull request merged**
